### ISSUE TITLE
Html Minifier is replacing variables starting `--_` with `-\5f`

### ISSUE THREAD

**Issue by Mehuge** [trullock/NUglify#302]
The following CSS is not minifying correctly:
```css
[part="resize-handle"] {
  background-color: var(--_lumo-grid-secondary-border-color) !important;
  opacity: 1 !important;
  width: 0 !important;
}
```
The `background-color` property is minified to
```css
background-color: var(-\5flumo-grid-secondary-border-color) !important;
```
The code used to minify is as follows:
```c#
var htmlSettings = new HtmlSettings();
htmlSettings.JsSettings.MinifyCode = false;
htmlSettings.JsSettings.LocalRenaming = LocalRenaming.KeepAll;
var result = Uglify.Html(File.ReadAllText(serverBundle), htmlSettings);
```
It appears that anywhere a variable reference `var(...)` starts with `--_` it is replaced with `-\5f`
