### ISSUE TITLE
Minify empty CSS variable raises error CSS1036

### ISSUE THREAD

**Issue by rwasef1830** [trullock/NUglify#331]
Hello,
The following CSS (appears in Bootstrap 5.2.0 release compiled SCSS) triggers error CSS1036 however, it's actually a valid expression:

```css
.btn {
  --bs-btn-font-family: ;
}
```

Reference: https://github.com/twbs/bootstrap/issues/36508
