### ISSUE TITLE
Tailwind css with non trailing semicolon produces error CSS1036: Expected expression found '}'

### ISSUE THREAD

**Issue by jafin** [trullock/NUglify#407]
Are you using the latest verion of NUglify, especially if used through BunderMinifier?  **Yes**

**Describe the bug**
Tailwind can have the following CSS:

```css
*, ::before, ::after {
  --tw-contain-paint:  ;
  --tw-contain-style:  
}
```

Ending semicolons are not mandatory
NUglify will parse the content but produce the error

```text
CSS1036: Expected expression found '}'
```

**To Reproduce**
```c#
   var text = @"
::before {
    --tw-contain-style:  
}";
        var result = Uglify.Css(text, new CssSettings(){});
result.
        Assert.False(result.HasErrors);
```

**Excepted output code**
Expect can parse this css without error.
